### ISSUE TITLE
is this archetype up to date?

### ISSUE THREAD

**Issue by zak905** [GwtMaterialDesign/gwt-material-archetype#7]
I was wondering if this is the official archetype for GwtMaterialDesing, or there is another one. 

I got an AST error while trying to run it.
[INFO] Compiling module com.gwidgets.materialtheme.GwtMaterialBasic
[INFO]    [ERROR] An internal compiler exception occurred
[INFO] com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:121)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:296)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
[INFO]  at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:67)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
[INFO]  at com.google.gwt.dev.jjs.ast.JMethodCall.visitChildren(JMethodCall.java:253)
[INFO]  at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:246)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
[INFO]  at com.google.gwt.dev.jjs.ast.JExpressionStatement.traverse(JExpressionStatement.java:42)
[INFO]  at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:95)

 I also had to change the packaging from jar to pom to be able to use the archetype locally.  I think also it is better to prompt the user for the module name when generating the project as in : https://github.com/tbroyer/gwt-maven-archetypes

**Comment by kevzlou7979** [comment]
Hi there, Yes this is up to date, as we are generating our sample test demo (1.6.x) successfully. There might be a problem into your Maven dependencies (I got often this error because of the SErvlet issue version inconsistency which was not on 1.6.x but for 2.0-SNAPSHOT (On going archetype https://github.com/GwtMaterialDesign/gwt-material-archetype/pull/6). But yes if you found any culprit and also the prompting of module name please feel free to submit a PR.

Thanks,
Kevin

**Comment by kevzlou7979** [comment]
Ok we have release a stable archetype for 2.0-rc1
