### ISSUE TITLE
[QUESTION] How do you "run" the application after you generate it

### ISSUE THREAD

**Issue by stuckless** [GwtMaterialDesign/gwt-material-archetype#8]
This might be an obvious question, but after I create a sample application, how do run/test it?

when I use mvn gwt:run I get a window pop up that has a button to launch the html, but that opens a browser with a 404 error?  Just trying figure out the basics here :(

**Comment by stuckless** [comment]
I should add, I can run this if I create a run configuration in IntelliJ (probably same for Eclipse), but since this creates a pom.xml, I figured you should be able to run it directly from Maven as well.  Is that not the case?

**Comment by kevzlou7979** [comment]
You need to `mvn clean install` before `mvn gwt:run`.
Other resource https://www.youtube.com/watch?v=sEVqfqDUOpE

**Comment by stuckless** [comment]
Thanks... appreciate the `mvn clean install` ... Missed that.   I do notice that many projects don't actually include information on how to run the app after you check it out, etc.   Seems like it would be something pretty easy to add to the readme.md file.   I might update the readme for future reference.   I've used GWT for a long time, just not with Maven (eclipse and intellij) so I could easily run the app, but, I also wanted to know how to run it using maven (and now I know).  thx.  I also appreciate the work on this project (GWD) since GWT has been missing a nice set of UI widgets for a long time.

**Comment by kevzlou7979** [comment]
Yeah no problem please submit a PR for the update :) we appreciate it also
